version: '3.8'

services:
  credly-scraper:
    build: .
    container_name: credly-scraper
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./output:/output
    command: python3 main.py
    restart: unless-stopped
